#!/bin/bash

# python writes trans summ file to ../SummaryFiles/ -- Time Stamped
# read in local valid accounts

cd Sessions

for i in *.txt
do 
	echo "running $i"
	FILE="$i"
	cat $FILE | while read line 
	do
		echo $line
	done | python ../breakingbank.py 
done

cd ..

cd SummaryFiles 

#!/bin/bash
for i in *.txt
do
	echo "merging $i"
	cat "$i" >> ../mergedtransactions.txt
	printf "\n" >> ../mergedtransactions.txt
done

cd .. 

python breakingbank-backend.py

echo -n "" > mergedtransactions.txt # empties merged transactions at complete end of day