#!/bin/bash

# === Day 1 ===

echo "=== Day 1 ==="
cp WeeklySessions/Day1/. DailySessions
./daily
cd DailySessions
rm *
cd ..

# === Day 2 ===

echo "=== Day 2 ==="
cp WeeklySessions/Day2/. DailySessions
./daily
cd DailySessions
rm *
cd ..

# === Day 3 ===

echo "=== Day 3 ==="
cp WeeklySessions/Day3/. DailySessions
./daily
cd DailySessions
rm *
cd ..

# === Day 4 ===

echo "=== Day 4 ==="
cp WeeklySessions/Day4/. DailySessions
./daily
cd DailySessions
rm *
cd ..

# === Day 5 ===

echo "=== Day 5 ==="
cp WeeklySessions/Day5/. DailySessions
./daily
cd DailySessions
rm *
cd ..
