#!/bin/bash

# === Day 1 ===

echo "=== Day 1 ==="
cp WeeklySessions/Day1/. DailySessions
./daily
cd DailySessions
rm *
cd ..
cat mergedtransactions.txt > Day1Merged.txt
cat masteraccounts.txt > Day1Master.txt
echo -n "" > mergedtransactions.txt

# === Day 2 ===

echo "=== Day 2 ==="
cp WeeklySessions/Day2/. DailySessions
./daily
cd DailySessions
rm *
cd ..
cat mergedtransactions.txt > Day1Merged.txt
cat masteraccounts.txt > Day2Master.txt
echo -n "" > mergedtransactions.txt

# === Day 3 ===

echo "=== Day 3 ==="
cp WeeklySessions/Day3/. DailySessions
./daily
cd DailySessions
rm *
cd ..
cat mergedtransactions.txt > Day1Merged.txt
cat masteraccounts.txt > Day3Master.txt
echo -n "" > mergedtransactions.txt

# === Day 4 ===

echo "=== Day 4 ==="
cp WeeklySessions/Day4/. DailySessions
./daily
cd DailySessions
rm *
cd ..
cat mergedtransactions.txt > Day1Merged.txt
cat masteraccounts.txt > Day4Master.txt
echo -n "" > mergedtransactions.txt

# === Day 5 ===

echo "=== Day 5 ==="
cp WeeklySessions/Day5/. DailySessions
./daily
cd DailySessions
rm *
cd ..
cat mergedtransactions.txt > Day1Merged.txt
cat masteraccounts.txt > Day5Master.txt
echo -n "" > mergedtransactions.txt
