#!/bin/bash
cd inputs
for i in *.txt
do 
	echo "running $i"
	FILE="$i"
	cat $FILE | while read line 
	do
		echo $line
	done | python ../breakingbank.py > ../expected/$i.log
	cp ./tempsummfile.txt ../expected/$i.sum
	rm ./tempsummfile.txt
done
