#!/bin/bash
cd inputs
for i in *.txt
do 
	FILE="$i"
	cat $FILE | while read line 
	do
		echo $line
	done | python ../breakingbank.py > ../outputs/$i.log
	cp ./tempsummfile.txt ../outputs/$i.sum
	rm ./tempsummfile.txt
done