#!/bin/bash

# === Day 1 ===

echo "=== Day 1 ==="
cp WeeklySessions/Day1/* DailySessions
./daily
cd DailySessions
rm *
cd ..
cp SummaryFiles/* OldSummaryFiles
cd SummaryFiles
rm *
cd ..
cat mergedtransactions.txt > Day1Merged.txt
cat masteraccounts.txt > Day1Master.txt
echo -n "" > mergedtransactions.txt

